// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fab.insert.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFAB = `-- name: InsertFAB :one
INSERT INTO food_and_beverage (name, type, image_url, price)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertFABParams struct {
	Name     string      `json:"name"`
	Type     FabTypes    `json:"type"`
	ImageUrl pgtype.Text `json:"image_url"`
	Price    int32       `json:"price"`
}

func (q *Queries) InsertFAB(ctx context.Context, arg InsertFABParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertFAB,
		arg.Name,
		arg.Type,
		arg.ImageUrl,
		arg.Price,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
