// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fab.delete.sql

package sqlc

import (
	"context"
)

const deleteFAB = `-- name: DeleteFAB :exec
UPDATE food_and_beverage
SET is_deleted = true,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteFAB(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFAB, id)
	return err
}
