// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fab.delete.sql

package sqlc

import (
	"context"
)

const toggleFABDelete = `-- name: ToggleFABDelete :exec
UPDATE foods_and_beverages
SET is_deleted = NOT is_deleted,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ToggleFABDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, toggleFABDelete, id)
	return err
}
