// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fab.update.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateFAB = `-- name: UpdateFAB :exec
UPDATE food_and_beverage
SET name = $2,
    type = $3,
    image_url = $4,
    price = $5,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = false
`

type UpdateFABParams struct {
	ID       int32       `json:"id"`
	Name     string      `json:"name"`
	Type     FabTypes    `json:"type"`
	ImageUrl pgtype.Text `json:"image_url"`
	Price    int32       `json:"price"`
}

func (q *Queries) UpdateFAB(ctx context.Context, arg UpdateFABParams) error {
	_, err := q.db.Exec(ctx, updateFAB,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.ImageUrl,
		arg.Price,
	)
	return err
}
