// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fab.update.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateFAB = `-- name: UpdateFAB :exec
UPDATE foods_and_beverages
SET name = $2,
    type = $3,
    price = $4,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = false
`

type UpdateFABParams struct {
	ID    int32    `json:"id"`
	Name  string   `json:"name"`
	Type  FabTypes `json:"type"`
	Price int32    `json:"price"`
}

func (q *Queries) UpdateFAB(ctx context.Context, arg UpdateFABParams) error {
	_, err := q.db.Exec(ctx, updateFAB,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Price,
	)
	return err
}

const updateFABImageURL = `-- name: UpdateFABImageURL :exec
UPDATE foods_and_beverages
SET image_url = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateFABImageURLParams struct {
	ImageUrl pgtype.Text `json:"image_url"`
	ID       int32       `json:"id"`
}

func (q *Queries) UpdateFABImageURL(ctx context.Context, arg UpdateFABImageURLParams) error {
	_, err := q.db.Exec(ctx, updateFABImageURL, arg.ImageUrl, arg.ID)
	return err
}
