// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: film.delete.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllFilmGenresByFilmID = `-- name: deleteAllFilmGenresByFilmID :exec
DELETE FROM film_genres
WHERE film_id = $1
`

func (q *Queries) deleteAllFilmGenresByFilmID(ctx context.Context, filmID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, deleteAllFilmGenresByFilmID, filmID)
	return err
}
