// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOutbox(ctx context.Context, arg CreateOutboxParams) error
	GetAllFilms(ctx context.Context) ([]GetAllFilmsRow, error)
	GetFABById(ctx context.Context, id int32) (FoodsAndBeverage, error)
	GetFABImageURLByID(ctx context.Context, id int32) (pgtype.Text, error)
	GetFilmById(ctx context.Context, id int32) (GetFilmByIdRow, error)
	GetFilmByTitle(ctx context.Context, title string) (Film, error)
	GetFilmDuration(ctx context.Context, id int32) (pgtype.Interval, error)
	GetPosterUrlByFilmId(ctx context.Context, filmID int32) (pgtype.Text, error)
	GetPriceOfFABById(ctx context.Context, id int32) (int32, error)
	GetTrailerUrlByFilmId(ctx context.Context, filmID int32) (pgtype.Text, error)
	InsertFAB(ctx context.Context, arg InsertFABParams) (int32, error)
	IsFABExist(ctx context.Context, id int32) (bool, error)
	IsFilmExist(ctx context.Context, id int32) (bool, error)
	ListFAB(ctx context.Context) ([]FoodsAndBeverage, error)
	ToggleFABDelete(ctx context.Context, id int32) error
	UpdateFAB(ctx context.Context, arg UpdateFABParams) error
	UpdateFABImageURL(ctx context.Context, arg UpdateFABImageURLParams) error
	UpdatePosterUrlAndCheckStatus(ctx context.Context, arg UpdatePosterUrlAndCheckStatusParams) error
	UpdateVideoUrlAndCheckStatus(ctx context.Context, arg UpdateVideoUrlAndCheckStatusParams) error
	deleteAllFilmGenresByFilmID(ctx context.Context, filmID pgtype.Int4) error
	insertFilm(ctx context.Context, arg insertFilmParams) (int32, error)
	insertFilmChange(ctx context.Context, arg insertFilmChangeParams) error
	insertFilmGenre(ctx context.Context, arg insertFilmGenreParams) error
	insertOtherFilmInformation(ctx context.Context, arg insertOtherFilmInformationParams) error
	updateFilm(ctx context.Context, arg updateFilmParams) error
	updateFilmChange(ctx context.Context, arg updateFilmChangeParams) error
	updateFilmInformation(ctx context.Context, arg updateFilmInformationParams) error
}

var _ Querier = (*Queries)(nil)
