// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetAllFilms(ctx context.Context) ([]GetAllFilmsRow, error)
	GetFilmByTitle(ctx context.Context, title string) (Films, error)
	UpdatePosterUrlAndCheckStatus(ctx context.Context, arg UpdatePosterUrlAndCheckStatusParams) error
	UpdateVideoUrlAndCheckStatus(ctx context.Context, arg UpdateVideoUrlAndCheckStatusParams) error
	insertFilm(ctx context.Context, arg insertFilmParams) (int32, error)
	insertFilmChange(ctx context.Context, arg insertFilmChangeParams) error
	insertFilmGenre(ctx context.Context, arg insertFilmGenreParams) error
	insertOtherFilmInformation(ctx context.Context, arg insertOtherFilmInformationParams) error
}

var _ Querier = (*Queries)(nil)
